### ISSUE TITLE
unit tests problem

### ISSUE THREAD

**Issue by ellis2323** [aergoio/SMT#1]
# github.com/aergoio/aergo-lib/db
/home/ellis/Documents/Golang/src/github.com/aergoio/aergo-lib/db/badgerdb.go:130:15: assignment mismatch: 2 variables but 1 values
/home/ellis/Documents/Golang/src/github.com/aergoio/aergo-lib/db/badgerdb.go:130:28: not enough arguments in call to item.Value
	have ()
	want (func([]byte) error)
/home/ellis/Documents/Golang/src/github.com/aergoio/aergo-lib/db/badgerdb.go:249:30: too many arguments in call to transaction.tx.Commit
	have (nil)
	want ()
/home/ellis/Documents/Golang/src/github.com/aergoio/aergo-lib/db/badgerdb.go:335:14: assignment mismatch: 2 variables but 1 values
/home/ellis/Documents/Golang/src/github.com/aergoio/aergo-lib/db/badgerdb.go:335:39: not enough arguments in call to iter.iter.Item().Value
	have ()
	want (func([]byte) error)
FAIL	github.com/aergoio/SMT [build failed]
Error: Tests failed.

**Comment by paouvrard** [comment]
have you tried installing dependencies with '$glide install' instead ?

**Comment by ellis2323** [comment]
my bad... i tought i have done it.
With glide install, it's ok
