### ISSUE TITLE
Can I open multiple tries on single db?

### ISSUE THREAD

**Issue by GrapeBaBa** [aergoio/SMT#2]
Can I open multiple tries on single db? Such as Ethereum, it use single leveldb for man account trie and    
all storage tries?

**Comment by paouvrard** [comment]
Yes. You can also have multiple trie objects of the same trie stored in db if you set the trie root manually after another trie has been update. For state storage, cheaper merkle proofs verification and high throughput trie updates i'd recommend : [https://github.com/aergoio/aergo/tree/master/pkg/trie](https://github.com/aergoio/aergo/tree/master/pkg/trie)

**Comment by GrapeBaBa** [comment]
@paouvrard Thanks, I looked at  https://github.com/aergoio/aergo/blob/master/contract/vm.go#L467-L471 these codes. It seems there is a bug since it passed actual code bytes, however the getContract method read codelength again.

**Comment by eve2adam** [comment]
@GrapeBaBa Thanks for report. it's not a bug because deployed code have first length (code + constructor args) and second length (code + abi). actual and stored code have second length(code + abi) so getContract method need to read codelength
